server {
    listen 80;
    server_name localhost;

    access_log /var/log/nginx/nagios_access.log;
    error_log /var/log/nginx/nagios_error.log;

    auth_basic "Acceso Restringido - Nagios Admin";
    auth_basic_user_file /etc/nagios4/htpasswd.users;

    root /usr/share/nagios4/htdocs;
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Procesamiento de archivos PHP para el panel web
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
    }

    # Procesamiento de ejecutable CGI propio de Nagios
    location ~ \.cgi$ {
        root /usr/lib/cgi-bin/nagios4;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /usr/lib/cgi-bin/nagios4$fastcgi_script_name;
        fastcgi_pass unix:/var/run/fcgiwrap.socket;
    }
}